### ISSUE TITLE
This library shouldn't have been created

### ISSUE THREAD

**Issue by Kurzdor** [scarf-sh/scarf-js#24]
TL;DR: I created a gist which can patch this spyware/trojan/rootkit with my [Gist ](https://gist.github.com/Kurzdor/bd5c18861b76eb34f068bf2ed7de903e)which replaces this lib on postinstall because npm/yarn gives you an ability to install it like any package to node_modules.

Before you install it, delete your local project @scarf/scarf folder in node_modules if present (probably you are using some of [this packages](https://www.npmjs.com/package/@scarf/scarf?activeTab=dependents))

Install gist mock version instead of local project version which sends your data with this commands depending of package manager you use:

```sh
npm install --save-dev gist:bd5c18861b76eb34f068bf2ed7de903e
yarn add gist:bd5c18861b76eb34f068bf2ed7de903e --dev
pnpm install --save-dev gist:bd5c18861b76eb34f068bf2ed7de903e
```

This mock gist just gives you clear vision on what is running on postinstall, it just outputs that scarf was mocked with one only console.log.

Also you can opt out from running postinstall scripts using npm install --ignore-scripts, yarn install --ignore-scripts or, if you use pnpm, pnpm install --ignore-scripts.
But be careful because some your packages will not work, like node-sass because they require compiling it or etc.
Or they just ask you to fund them which is good because you support good open-source developers and their works like the main JS polyfill on which works babel - core-js. Better support its developer for his job for JS ecosystem.

Or you manually run postinstall hooks for each package you need by running it in node_modules/dependency_that_needs_building_or_compiling

You can globally disable running postinstall via npm/yarn/pnpm config to be more secure (don't forget about vulnerabilities like:
https://www.zdnet.com/article/microsoft-spots-malicious-npm-package-stealing-data-from-unix-systems/
https://www.zdnet.com/article/cryptocurrency-startup-hacks-itself-before-hacker-gets-a-chance-to-steal-users-funds/
https://www.zdnet.com/article/hacker-backdoors-popular-javascript-library-to-steal-bitcoin-funds/
https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes
https://blog.npmjs.org/post/173526807575/reported-malicious-module-getcookies
https://twitter.com/o_cee/status/892306836199800836)
https://medium.com/@jsoverson/how-two-malicious-npm-packages-targeted-sabotaged-one-other-fed7199099c8
Also there was a lib which did similar things and it was deleted by NPM. (1337qq-js)

I am working on scarf patcher which will on library blacklist patch your package.json with this gist instead of running scarf:
https://www.npmjs.com/package/itssummernoscarfs

Well, let me explain a bit why it is bad idea.
So, you say this is "Google Analytics-like" for OSS libs, but NPM gives you ability to see how much users installed per week.
BTW, this package has ~300k downloads per week only because of redux-form, final-form, react-table.
Why do you need to see which OS users install lib?
There is 3 main OS: Windows (+Windows Subsystem for Linux), Linux, MacOS.
Look at the most popular from StackOverflow Survey 2020:
https://insights.stackoverflow.com/survey/2020#technology-platforms
Also, users when create issue tell you what OS they use.
Next, the OS architecture. Are you sure that architecture value will break lib? There is 3 most popular architectures: x64, x32 (x86) and ARM.
Library users can talk via issues if anybody has some problems even without scarfjs.
Also as I heard library sends IP adresses, what means also country and city to your server and, maybe, deletes it or not, but we don't know yet, we don't see the server code.
Also you are not protected from hacking your database, server or other and leaking data.
Somebody mentioned later that this library not GDPR-friendly and don't forget about NDA, because it's can be private or etc.
There is variant of creating issue like "Who uses *?" and there is a choice to say about company or no. What if my project is private and I doesn't want to leak any data about it?
Why this library gets data about my dependency list? You tell that is gets info about most used lib combo with those who has @scarf/scarf in their dependencies but then you say "Limited dependency tree information. Scarf sends the name and version of the package(s) that directly depend on scarf-js". What I think as lib user I mentioned above.
It sends data on EACH install and doesn't opt-out by default and there is already 300k download and it is used in ~1300 repos on GitHub regarding with "Used by" section on https://github.com/scarf-sh/scarf-js.
Also it takes some time to run every time it's postinstall script and can take up to minute depending on project.
Also, I forget it WILL run on CI every time on build!

I think this is spyware/rootkit/trojan which cannot be predicted in future, it looks like cancer of JS ecosystem and like any disease has to be cure at the very start/has to be deleted by antivirus before it could be worse.

**Comment by aviaviavi** [comment]
Hi @Kurzdor, thank you for taking the time to voice your concerns. There are many points to unpack here and respond to:

Yes, npm tells you how many downloads your package has. They actually know and collect quite a bit more information than that and could safely expose that information to package maintainers, but they choose not too. scarf-js fills those gaps to give maintainers insight into their own software's usage. 

Collecting the OS can be useful to maintainers in all sorts of ways. Just knowing the global breakdown of OS's from developers is nice, but that doesn't mean the user-base of your package follows the same breakdown. While node is cross-platform, there are lots of node API's that behave differently on various operating systems and therefore lots of potential for platform-specific bugs. Having access to that information can be useful to maintainers for things like prioritizing bug fixes. Same goes for architecture.

> Library users can talk via issues if anybody has some problems even without scarfjs.

This is true. This is starting to get at a problem in OSS: we only hear about issues when people report them, and only the people complaining the loudest get help. Having some basic analytics helps mitigate this issue, as maintainers can pro-actively spot problems and more objectively prioritize them.

> There is variant of creating issue like "Who uses *?" and there is a choice to say about company or no. What if my project is private and I doesn't want to leak any data about it?

If your project is private, you can opt-out of the analytics, easily. We have tried to make this as easy as possible via multiple opt-out methods, and are happy to add more that better suit your workflow. However, even leaving analytics on doesn't actually leak any information about your project other than informing the maintainer that your company is using a given software package. Knowing who your commercial users are can be very helpful to maintainers. Opening an issue to ask people to report if their employer uses a package is fine, but having this done automatically is a more effective solution.

> Somebody mentioned later that this library not GDPR-friendly and don't forget about NDA, because it's can be private or etc.

This is not actually correct though. scarf-js doesn't collect personally-identifying info. We're only interested in anonymized data that helps with maintenance and information about companies using a piece of software, which can help maintainers set up sponsorships, support agreements, etc to financially support their projects.

> Also you are not protected from hacking your database, server or other and leaking data.

True. The same can be said of any package manager too as they collect this data but also a lot more in most cases. Scarf is just providing some of this information back to the actual maintainers, which something package managers could (and should) be doing already. Scarf takes security very seriously and takes industry-standard precautions to prevent this.

> Why this library gets data about my dependency list?

The snippet of the README quoted here is out of date. Scarf only sends hashes of some packages in the dependency list, which enables matching up publicly listed packages in the dependency tree while still keeping all private packages fully private. It helps maintainers to know which packages are being installed alongside of theirs, which can be highly informative for maintainers.

> Also it takes some time to run every time it's postinstall script and can take up to minute depending on project.  Also, I forget it WILL run on CI every time on build!

If your CI has absolutely no caching set up, then yes, analytics will fire every time. Still, you can opt-out of scarf's analytics via multiple ways, and we are happy to add any other methods of opting out that fits better with your workflow. Though if you want to simply maintain your new npm package for mocking scarf analytics, you are obviously free to do that too.

Overall, I must disagree that this library is a "cancer", "rootkit", "trojan" or otherwise. The analytics that scarf-js provides helps open source maintainers understand how their software is being used and doesn't collect any information that npm isn't already collecting. We're just trying to put that data into the hands of the people who are distributing amazing software for free, and that helps everyone. We're trying to do this as securely and responsibly as we can. The malicious packages you linked to collect very invasive data like system processes and environment variables, which we are in no way collecting here. If you have actionable ideas for ways we can make the library more secure, faster, or better in any way than I am all ears! But simply suggesting we delete the library is unfortunately not constructive here.

**Comment by Kurzdor** [comment]
@aviaviavi, thanks for your response.

> could safely expose that information to package maintainers, but they choose not too

Then why not to ask them to do it, it is much better, no? It's better to keep all environmental data in one place, like NPM, not having it spreaded across other servers, like yours. Or just better use one issue where user can just take part in poll via emotes.

It's developer's problem if he/she can't organize their issues with badges, which really help in searching OS-related bugs. If a lot of users encounter then it will be solved much faster and Scarf won't tell OSS developer about problem so Scarf is only a installation counter, which I mention again available on NPM package page.

> Having access to that information can be useful to maintainers for things like prioritizing bug fixes

I agree with you, but it shouldn't be handled by 3rd party library. Nevertheless, OSS developer can himself/herself can prioritize issue fix priority by counting of user encountering the issue, by difficulty of fixing it, is it critical or no.

> you can opt-out of the analytics, easily

Well, I don't wanna to trash my package.json or my script, using environmental variables with scarfAnalytics key/section only because that library developer uses Scarf. Even how much it could be easy in your opinion, it's not my need like ESLint, Prettier or other really helpful tools for me and other developers. Library users will switch or use their forks without Scarf and ruin OSS developer's work and funding.

> However, even leaving analytics on doesn't actually leak any information about your project other than informing the maintainer that your company is using a given software package

One malicious pull request/account hack will really "don't leak any information" and even more information than library collects now. It's also creates some thoughts if it safe use xyz library today or no? 

> Opening an issue to ask people to report if their employer uses a package is fine, but having this done automatically is a more effective solution.

I really don't understand how will you determine on which company machine will it run?  =) Like I said if I don't know about change in my favorite library and this package that sends data about my machine even if it can be sensitive.

> scarf-js doesn't collect personally-identifying info

The IP address, isn't it? Should I mention what is static/dynamic IPs? Country? Company if it even works? The full usage statistics gives you: NPM via download/week, GitHub: "Used in" section, forks, stars, etc. Why even it gets info about my location/country, what's the reason and usecase except of statistics? You know that English is universal language everywhere and also in JS ecosystem if we are talking about GitHub right now for example. About company I explained above.

> The same can be said of any package manager

Thing is that package manager doesn't have own backend, it's global NPM repository, in China for its residents and other package repository/CDN like [pika.dev](https://www.pika.dev/cdn) or other repositories that I don't know right know.

> still keeping all private packages fully private

Scarf doesn't respect package.json's "private": true as I see in code. There is only default return of "@private/private": "0" if crypto is not available (which is already in node installation box).

>alongside of theirs, which can be highly informative for maintainers

I have installed react and react-dom with react-final-form. Really worth sending info imo. Ok, it can be useful if somebody uses old version of framework and old version of scarfed library just to give info to OSS developer to keep maintaining it. This is if we talk about pair framework+library which is built with it. And what about other non framework-libraries like date-fns or dayjs, e.g? I don't see reason sending it, sorry. Explain me it if I probably don't understand it.

> Overall, I must disagree that this library is a "cancer", "rootkit", "trojan" or otherwise

I said it only because it can be really bad or even malicious. And now all I see is the new cancer/disease/possible rootkit/possible trojan that installs and runs without my agree and I have to prepare settings just for it to be disabled. It works very similar to things I mentioned above and should be cured before it's widespread. Now it was installed 300k times and used in 1300 repositories. I don't mind having to see funding request from developer which package I use and even support him if it is possible for me. But having this thing is inappropriate even if it has options to opt-it. People like i said will use other solutions or fork their work and fix this shit.

Since this is new package it is not that wide-spread between JS developers and they don't know about it right now but like I said it takes some time to run postinstall script even in yarn. And what if I use one package across several projects? Why I need to have other routine just to disable analytics?

My opinion about this library that this doesn't have any sense in current state and it can be very malicious and really interesting target for hackers (don't think me paranoid) and I don't want any unwanted library to run. And I already told all my other thoughts above. I should mention that I can fake packages stats just by knowing where and what info to send. Your API key mentioned on account page won't help prevent it.

This library shouldn't be shipped with package that I requested. If I want, I can run scarfjs and share with it. Normal software ask user before sending any info, even basic because user has his/her thought about sending or not any of his/her data. Read globally stored environmental variables but not storing settings to disable it per-project.

**Comment by aviaviavi** [comment]
@Kurzdor:

> One malicious pull request/account hack will really "don't leak any information" and even more information than library collects now.

I understand your concern here. But this is true of every library you use on npm or any other package registry. Any dependency is just one hack away from doing something malicious. But that's not a reason to not write software the can help people - It's a reason to be very security conscious, which I can assure you, we are. We are committed to making sure scarf-js does analytics securely, and only collect information that can directly help developers either maintain their project or financially support their project.

> Thing is that package manager doesn't have own backend

They do actually. Package managers are just a frontend to package registries, which are the backend.

> Well, I don't wanna to trash my package.json or my script, using environmental variables with scarfAnalytics key/section only because that library developer uses Scarf

You don't need any keys for the environment variable, just setting `SCARF_ANALYTCS=false` will do it. I don't necessarily agree that adding a single variable to your package.json is "trashing" it, but I understand if that solution isn't for you. Let us know if there's another method that would work better for you. 

> Scarf doesn't respect package.json's "private": true as I see in code

It doesn't need to do this anymore, as we only send hashes of package names, not the names themself. If that name is not published to npm, we have no way of knowing what the package is, no real information has been leaked.

> The IP address, isn't it? Should I mention what is static/dynamic IPs? Country? Company if it even works? 

The IP address is used to look up any available company information. Yes, this approach is far from perfect, but it still works in many cases. Knowing the company information allows maintainers to contact these businesses for sponsorships, and knowing if that company is local, even better. In any case, the IP address is immediately deleted on our side after the metadata is looked up. We're just trying to help OSS developers and these analytics are directly to that end.

> I have installed react and react-dom with react-final-form. Really worth sending info imo. Ok, it can be useful if somebody uses old version of framework and old version of scarfed library just to give info to OSS developer to keep maintaining it. This is if we talk about pair framework+library which is built with it. And what about other non framework-libraries like date-fns or dayjs, e.g? I don't see reason sending it, sorry. Explain me it if I probably don't understand it.

If it sounds like being able to control which packages can report analytics without globally opting out, we can add this to Scarf for you! Right now you're either fully opt-in or opt-out, but that can be changed.

> Why I need to have other routine just to disable analytics?

Because the software you are using is the hard work of other people, and it helps them to know how their projects are being used. The alternate methods of collecting data that you mention are either insufficient or unavailable. If you want to opt-out, that's fine, but that doesn't mean it's wrong for maintainers to collect that information using scarf-js. Just asking people via a survey is not an effective way to collect this information.

I hope this addresses your concerns but I also understand that you feel strongly enough about this that I may not be able to convince you that what we're doing is actually a good thing. We can keep talking here or I could even chat about this over the phone to dive into it more.

**Comment by dalisoft** [comment]
This is most needed feature/tool, maintainers of **scarf-js** should continue development. I'm as author of some OSS project support this way of supporting authors to getting information about package users.

**Comment by Kurzdor** [comment]
> This is most needed feature/tool, maintainers of **scarf-js** should continue development. I'm as author of some OSS project support this way of supporting authors to getting information about package users.

If it is that needed thing in OSS, then you and other developers should ask NPM for this feature, no? 
People said their opinions about having buttplug in their projects. Most libs that used Scarf already removed it and I am happy about it. I still don't understand from what source author of Scarf gets info company.
This is the same cancer as some developers put postinstall banners that can be too big asking for funding. This is bad option. Don't think I don't support the work that you and other devs put in libraries that they develop.
NPM added ```fund``` option and any user that can support it can do it. You got Sponsoring section in GitHub. Then why not ask NPM/other repos to add stats about OS usage for library that can be only visible for developer? Read NPM's privacy policy and what they collect. I don't mind about that data that they collect, but not when 3rd party script send data about user and company. This is disgusting. Project Managers and other Managers won't be happy about that. Also developers should not email to companies and ask if "premium help" is needed. Company should do it instead. Also Company can and should take decision to fund/sponsor developer.

**Comment by dalisoft** [comment]
@Kurzdor I also added and removed after day usage. It's collects more data than expected, so i think not good idea to add this library to dependencies

**Comment by Kurzdor** [comment]
> @Kurzdor I also added and removed after day usage. It's collects more data than expected, so i think not good idea to add this library to dependencies

People using old version still gonna run scarf postinstall.

**Comment by aviaviavi** [comment]
@Kurzdor:

> then you and other developers should ask NPM for this feature, no? ... Then why not ask NPM/other repos to add stats about OS usage for library that can be only visible for developer?

Why are you assuming this hasn't been asked for already? People _have_ asked for it. Maintainers requesting better information from package registries is not a new idea. But nothing has come of this - we remain in a position where they are not providing this data to maintainers even though they have it available for themselves. Until then, Scarf can help bridge that gap for maintainers.

> I still don't understand from what source author of Scarf gets info company.

As mentioned in the docs, we pay for API's to look up business metadata associated with IP addresses (Scarf doesn't store the IP's themselves) and provide the information to maintainers for free. https://ipregistry.co/, https://clearbit.com/, https://ipinfo.io/, are some examples, there are many.

> Also developers should not email to companies and ask if "premium help" is needed. Company should do it instead. Also Company can and should take decision to fund/sponsor developer.

I strongly disagree with this. Empowering maintainers to know who their commercial users are is an important step in making OSS more sustainable for the people who are creating it. What you are suggesting is to just keep everything the same, and right now maintainers are regularly burning out from the massive amount of work they put in to ensure their projects are reliable for their users. To keep things the same is to let companies take advantage of free work done by individuals, without providing anything in return. Sure, companies _can and should_ support the people who build the OSS they rely on, but for the most part, they don't.

>  Project Managers and other Managers won't be happy about that.

None of the telemetry affects end-users, it's only on `npm install`, so I actually don't see why this should be something a project manager would care about.

@dalisoft:

> I also added and removed after day usage. It's collects more data than expected, so i think not good idea to add this library to dependencies

What data were you not expecting Scarf to collect, specifically? Very little data is being collected here, no personally identifying information is being stored.

**Comment by Kurzdor** [comment]
@aviaviavi,
> People _have_ asked for it

Show me an example then because I don't even remember anything about this.

**Comment by aviaviavi** [comment]
@Kurzdor:

Here are two to npm directly:

https://github.com/npm/npm/issues/279
https://github.com/npm/www/issues/23

Here is a great talk I highly recommend which is aimed at the Ruby community, but the same idea. 

https://www.youtube.com/watch?v=hW4wUpoBHr8
